### ISSUE TITLE
time.sleep doesn't behave as it should

### ISSUE THREAD

**Issue by Talw3g** [Tibzor/ctahr#1]
@JDRobotter :
Especially in buttons.py, time.sleep behavior is awkward : it's set to [0.01s,](https://github.com/Tibzor/ctahr/blob/master/ctahr/buttons.py#L51) but when looking at the output it's more like 0.5-0.6s... And thus buttons module doesn't catch short pushes on reset_lever !

Same problem has been observed in main app.py when trying to make led_run for 0.01s every 1s.

**Comment by Talw3g** [comment]
Problem seems to come from DHT22 sensor communication : a dramatic drop in whole application speed is observed each time the data are fetched.
Slowing the fetching loop does make it better, but really not perfect...

**Comment by JDRobotter** [comment]
A new implementation for CtahrThermoHygroSensor has been pushed (29d079e).
